name: habit_builder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: 1.1.6
  flutter_screenutil: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Manrope-B
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
    - family: Manrope-EB
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.ttf
    - family: Manrope-EL
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
    - family: Manrope-L
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf
    - family: Manrope-M
      fonts:
        - asset: assets/fonts/Manrope-Medium.ttf
    - family: Manrope-R
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
    - family: Manrope-SB
      fonts:
        - asset: assets/fonts/Manrope-SemiBold.ttf
    - family: Klasik-R
      fonts:
        - asset: assets/fonts/Klasik Regular.otf
    - family: Klasik-RO
      fonts:
        - asset: assets/fonts/Klasik Rough.otf
    - family: Klasik-S
      fonts:
        - asset: assets/fonts/Klasik Shadow.otf